{ Parsed from Corelocation.framework CLErrorDomain.h }

{$ifdef TYPES}
{$ifndef CLERRORDOMAIN_PAS_T}
{$define CLERRORDOMAIN_PAS_T}

{$endif}
{$endif}

{$ifdef RECORDS}
{$ifndef CLERRORDOMAIN_PAS_R}
{$define CLERRORDOMAIN_PAS_R}

{$endif}
{$endif}

{$ifdef FUNCTIONS}
{$ifndef CLERRORDOMAIN_PAS_F}
{$define CLERRORDOMAIN_PAS_F}

{$endif}
{$endif}

{$ifdef EXTERNAL_SYMBOLS}
{$ifndef CLERRORDOMAIN_PAS_S}
{$define CLERRORDOMAIN_PAS_S}

{ External string constants }
var
  kCLErrorDomain: NSString; cvar; external;

{$endif}
{$endif}
